In [3]:
import pandas as pd
import numpy as np

In [10]:
df = pd.DataFrame({
    "cust_id": ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11"],
    "item_bought": [10, 7, 5, 4, 10000, 10, 5, 5, 7, np.nan, np.nan],
    "city": ["Bandung", "Jakarta", "Bogor", "Tangerang", "Bandung", "Bogor", "Bogor", "Bogor", "Bandung", "Jakarta", np.nan]
})

df

   cust_id  item_bought       city
0       C1         10.0    Bandung
1       C2          7.0    Jakarta
2       C3          5.0      Bogor
3       C4          4.0  Tangerang
4       C5      10000.0    Bandung
5       C6         10.0      Bogor
6       C7          5.0      Bogor
7       C8          5.0      Bogor
8       C9          7.0    Bandung
9      C10          NaN    Jakarta
10     C11          NaN        NaN

In [12]:
##check missing values

df.isna().sum()

cust_id        0
item_bought    2
city           1
dtype: int64

In [14]:
## handling missing values

In [16]:
## drop

df.dropna()

  cust_id  item_bought       city
0      C1         10.0    Bandung
1      C2          7.0    Jakarta
2      C3          5.0      Bogor
3      C4          4.0  Tangerang
4      C5      10000.0    Bandung
5      C6         10.0      Bogor
6      C7          5.0      Bogor
7      C8          5.0      Bogor
8      C9          7.0    Bandung

In [18]:
## fill

In [24]:
## numeric
df_clean = df.copy()
df_clean["item_bought"] = df["item_bought"].fillna(0)
df_clean

   cust_id  item_bought       city
0       C1         10.0    Bandung
1       C2          7.0    Jakarta
2       C3          5.0      Bogor
3       C4          4.0  Tangerang
4       C5      10000.0    Bandung
5       C6         10.0      Bogor
6       C7          5.0      Bogor
7       C8          5.0      Bogor
8       C9          7.0    Bandung
9      C10          0.0    Jakarta
10     C11          0.0        NaN

In [26]:

df_clean = df.copy()
df_clean["item_bought"] = df["item_bought"].fillna(df["item_bought"].mean())
df_clean

   cust_id  item_bought       city
0       C1         10.0    Bandung
1       C2          7.0    Jakarta
2       C3          5.0      Bogor
3       C4          4.0  Tangerang
4       C5      10000.0    Bandung
5       C6         10.0      Bogor
6       C7          5.0      Bogor
7       C8          5.0      Bogor
8       C9          7.0    Bandung
9      C10       1117.0    Jakarta
10     C11       1117.0        NaN

In [28]:

df_clean = df.copy()
df_clean["item_bought"] = df["item_bought"].fillna(df["item_bought"].median())
df_clean

   cust_id  item_bought       city
0       C1         10.0    Bandung
1       C2          7.0    Jakarta
2       C3          5.0      Bogor
3       C4          4.0  Tangerang
4       C5      10000.0    Bandung
5       C6         10.0      Bogor
6       C7          5.0      Bogor
7       C8          5.0      Bogor
8       C9          7.0    Bandung
9      C10          7.0    Jakarta
10     C11          7.0        NaN

In [30]:
##categorical

df_clean = df.copy()
df_clean["city"] = df["city"].fillna(df["city"].mode()[0])
df_clean

   cust_id  item_bought       city
0       C1         10.0    Bandung
1       C2          7.0    Jakarta
2       C3          5.0      Bogor
3       C4          4.0  Tangerang
4       C5      10000.0    Bandung
5       C6         10.0      Bogor
6       C7          5.0      Bogor
7       C8          5.0      Bogor
8       C9          7.0    Bandung
9      C10          NaN    Jakarta
10     C11          NaN      Bogor

In [4]:
df = pd.DataFrame({
    "cust_id": ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11"],
    "item_bought": [10, 7, 5, 4, 10000, 10, 5, 5, 7, 4, 5],
    "city": ["Bandung", "Jakarta", "Bogor", "Tangerang", "Bandung", "Bogor", "Bogor", "Bogor", "Bandung", "Jakarta", "Bogor"]
})

df

   cust_id  item_bought       city
0       C1           10    Bandung
1       C2            7    Jakarta
2       C3            5      Bogor
3       C4            4  Tangerang
4       C5        10000    Bandung
5       C6           10      Bogor
6       C7            5      Bogor
7       C8            5      Bogor
8       C9            7    Bandung
9      C10            4    Jakarta
10     C11            5      Bogor

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cust_id      11 non-null     object
 1   item_bought  11 non-null     int64
 2   city         11 non-null     object
dtypes: int64(1), object(2)
memory usage: 396.0+ bytes

In [11]:
## check outlier

## IQR

q1 = df["item_bought"].quantile(0.25)
q3 = df["item_bought"].quantile(0.75)

print(q1)
print(q3)

5.0
8.5

In [12]:
iqr = q3 - q1
print(iqr)

3.5

In [13]:
fence_low = q1 - 1.5 * iqr
fence_high = q3 + 1.5 * iqr

print(fence_low)
print(fence_high)

-0.25
13.75

In [ ]:
## outlier adalah data yang berada di luar fence_low dan fence_high
## fence_low adalah batas bawah
## fence_high adalah batas atas


df[(df["item_bought"] < fence_low) | (df["item_bought"] > fence_high)]

  cust_id  item_bought     city
4      C5        10000  Bandung

In [ ]:
##handling outlier