In [7]:
#creating Dataframe from list of list

In [4]:
import pandas as pd

In [11]:
list_data = [["C1", 5, "Jakarta"], ["C2", 7, "Bogor"], ["C3", 4, "Tanggerang"], ["C4", 2, "Jakarta"]]

In [1]:
df = pd.DataFrame(list_data, columns = ["customer_id", "bought", "city"])
df

NameError: name 'pd' is not defined

In [17]:
#creating Dataframe Numpy Array

In [19]:
import numpy as np

In [21]:
numpy_data = np.array(list_data)
numpy_data

array([['C1', '5', 'Jakarta'],
       ['C2', '7', 'Bogor'],
       ['C3', '4', 'Tanggerang'],
       ['C4', '2', 'Jakarta']], dtype='<U21')

In [27]:
df = pd.DataFrame(numpy_data, columns = ["customer_id", "bought", "city"])
df

  customer_id bought        city
0          C1      5     Jakarta
1          C2      7       Bogor
2          C3      4  Tanggerang
3          C4      2     Jakarta

In [31]:
dictionary_data = {"customer_id" : ["C1", "C2", "C3"],
                  "bought" : [5, 7, 2],
                   "city" : ["Jakarta", "Tangerang", "Bogor"]
                  }
dictionary_data

{'customer_id': ['C1', 'C2', 'C3'],
 'bought': [5, 7, 2],
 'city': ['Jakarta', 'Tangerang', 'Bogor']}

In [35]:
df = pd.DataFrame(dictionary_data)
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor

In [37]:
#Saving Dataframe

In [39]:
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor

In [49]:
df.to_csv("customer_info.csv", index = False)

In [53]:
df.to_excel("customer_info.xlsx", index = False)

In [57]:
#Load Dataframe

In [61]:
df = pd.read_csv("customer_info.csv")
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor

In [65]:
df = pd.read_excel("customer_info.xlsx")
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor

In [67]:
#Basic operation

In [6]:
df = pd.DataFrame({"customer_id" : ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10"],
                  "bought" : [5, 7, 2, 4, 5, 2, 5, 6, 1, 2],
                   "city" : ["Jakarta", "Tangerang", "Bogor", "Jakarta", "Tangerang", "Bogor", "Jakarta", "Tangerang", "Bogor", "Bogor"]
                  })

In [73]:
#Summary Info

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  10 non-null     object
 1   bought       10 non-null     int64
 2   city         10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [101]:
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor
3          C4       4    Jakarta
4          C5       5  Tangerang
5          C6       2      Bogor
6          C7       5    Jakarta
7          C8       6  Tangerang
8          C9       1      Bogor
9         C10       2      Bogor

In [103]:
df.describe()

          bought
count  10.000000
mean    3.900000
std     2.024846
min     1.000000
25%     2.000000
50%     4.500000
75%     5.000000
max     7.000000

In [105]:
#columns name

In [107]:
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor
3          C4       4    Jakarta
4          C5       5  Tangerang
5          C6       2      Bogor
6          C7       5    Jakarta
7          C8       6  Tangerang
8          C9       1      Bogor
9         C10       2      Bogor

In [111]:
df.columns

Index(['customer_id', 'bought', 'city'], dtype='object')

In [113]:
list(df.columns)

['customer_id', 'bought', 'city']

In [119]:
for i in list(df.columns):
    print(i)

customer_id
bought
city

In [121]:
#daraframe lenght

In [123]:
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor
3          C4       4    Jakarta
4          C5       5  Tangerang
5          C6       2      Bogor
6          C7       5    Jakarta
7          C8       6  Tangerang
8          C9       1      Bogor
9         C10       2      Bogor

In [125]:
df.shape

(10, 3)

In [135]:
#banyaknya baris
df.shape[0]

10

In [137]:
#banyaknya column
df.shape[1]

3

In [139]:
#values of a particular column

In [141]:
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor
3          C4       4    Jakarta
4          C5       5  Tangerang
5          C6       2      Bogor
6          C7       5    Jakarta
7          C8       6  Tangerang
8          C9       1      Bogor
9         C10       2      Bogor

In [143]:
df["customer_id"]

0     C1
1     C2
2     C3
3     C4
4     C5
5     C6
6     C7
7     C8
8     C9
9    C10
Name: customer_id, dtype: object

In [146]:
df["bought"]

0    5
1    7
2    2
3    4
4    5
5    2
6    5
7    6
8    1
9    2
Name: bought, dtype: int64

In [148]:
df["city"]

0      Jakarta
1    Tangerang
2        Bogor
3      Jakarta
4    Tangerang
5        Bogor
6      Jakarta
7    Tangerang
8        Bogor
9        Bogor
Name: city, dtype: object

In [150]:
#values of several columns

In [152]:
df[["customer_id", "bought"]]

  customer_id  bought
0          C1       5
1          C2       7
2          C3       2
3          C4       4
4          C5       5
5          C6       2
6          C7       5
7          C8       6
8          C9       1
9         C10       2

In [154]:
df[["customer_id", "city"]]

  customer_id       city
0          C1    Jakarta
1          C2  Tangerang
2          C3      Bogor
3          C4    Jakarta
4          C5  Tangerang
5          C6      Bogor
6          C7    Jakarta
7          C8  Tangerang
8          C9      Bogor
9         C10      Bogor

In [156]:
#first N rows

In [158]:
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor
3          C4       4    Jakarta
4          C5       5  Tangerang
5          C6       2      Bogor
6          C7       5    Jakarta
7          C8       6  Tangerang
8          C9       1      Bogor
9         C10       2      Bogor

In [160]:
df.head()

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor
3          C4       4    Jakarta
4          C5       5  Tangerang

In [162]:
df.head(2)

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang

In [164]:
df.head(10)

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor
3          C4       4    Jakarta
4          C5       5  Tangerang
5          C6       2      Bogor
6          C7       5    Jakarta
7          C8       6  Tangerang
8          C9       1      Bogor
9         C10       2      Bogor

In [166]:
#last n rows

In [168]:
df.tail()

  customer_id  bought       city
5          C6       2      Bogor
6          C7       5    Jakarta
7          C8       6  Tangerang
8          C9       1      Bogor
9         C10       2      Bogor

In [170]:
df.tail(2)

  customer_id  bought   city
8          C9       1  Bogor
9         C10       2  Bogor

In [ ]:
#randow n rows

In [172]:
df.sample()

  customer_id  bought       city
1          C2       7  Tangerang

In [174]:
df.sample(4)

  customer_id  bought       city
7          C8       6  Tangerang
1          C2       7  Tangerang
8          C9       1      Bogor
6          C7       5    Jakarta

In [176]:
#sorting data

In [178]:
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor
3          C4       4    Jakarta
4          C5       5  Tangerang
5          C6       2      Bogor
6          C7       5    Jakarta
7          C8       6  Tangerang
8          C9       1      Bogor
9         C10       2      Bogor

In [180]:
df.sort_values(by = "bought", ascending = False)

  customer_id  bought       city
1          C2       7  Tangerang
7          C8       6  Tangerang
0          C1       5    Jakarta
4          C5       5  Tangerang
6          C7       5    Jakarta
3          C4       4    Jakarta
2          C3       2      Bogor
5          C6       2      Bogor
9         C10       2      Bogor
8          C9       1      Bogor

In [184]:
df.sort_values(by = "bought")

  customer_id  bought       city
8          C9       1      Bogor
2          C3       2      Bogor
5          C6       2      Bogor
9         C10       2      Bogor
3          C4       4    Jakarta
0          C1       5    Jakarta
4          C5       5  Tangerang
6          C7       5    Jakarta
7          C8       6  Tangerang
1          C2       7  Tangerang

In [186]:
df.sort_values(by = ["bought", "customer_id"], ascending = False)

  customer_id  bought       city
1          C2       7  Tangerang
7          C8       6  Tangerang
6          C7       5    Jakarta
4          C5       5  Tangerang
0          C1       5    Jakarta
3          C4       4    Jakarta
5          C6       2      Bogor
2          C3       2      Bogor
9         C10       2      Bogor
8          C9       1      Bogor

In [195]:
df.sort_values(by = ["bought", "customer_id"], ascending = False).reset_index(drop = True)

  customer_id  bought       city
0          C2       7  Tangerang
1          C8       6  Tangerang
2          C7       5    Jakarta
3          C5       5  Tangerang
4          C1       5    Jakarta
5          C4       4    Jakarta
6          C6       2      Bogor
7          C3       2      Bogor
8         C10       2      Bogor
9          C9       1      Bogor

In [197]:
#rename columns

In [199]:
df

  customer_id  bought       city
0          C1       5    Jakarta
1          C2       7  Tangerang
2          C3       2      Bogor
3          C4       4    Jakarta
4          C5       5  Tangerang
5          C6       2      Bogor
6          C7       5    Jakarta
7          C8       6  Tangerang
8          C9       1      Bogor
9         C10       2      Bogor

In [203]:
df.rename(columns = {"customer_id": "cust_id", "bought": "num_of_item"})

  cust_id  num_of_item       city
0      C1            5    Jakarta
1      C2            7  Tangerang
2      C3            2      Bogor
3      C4            4    Jakarta
4      C5            5  Tangerang
5      C6            2      Bogor
6      C7            5    Jakarta
7      C8            6  Tangerang
8      C9            1      Bogor
9     C10            2      Bogor

In [213]:
df.columns = ["cust_id", "num_of_item", "user_city"]

In [215]:
df

  cust_id  num_of_item  user_city
0      C1            5    Jakarta
1      C2            7  Tangerang
2      C3            2      Bogor
3      C4            4    Jakarta
4      C5            5  Tangerang
5      C6            2      Bogor
6      C7            5    Jakarta
7      C8            6  Tangerang
8      C9            1      Bogor
9     C10            2      Bogor

In [217]:
#change data type

In [219]:
df

  cust_id  num_of_item  user_city
0      C1            5    Jakarta
1      C2            7  Tangerang
2      C3            2      Bogor
3      C4            4    Jakarta
4      C5            5  Tangerang
5      C6            2      Bogor
6      C7            5    Jakarta
7      C8            6  Tangerang
8      C9            1      Bogor
9     C10            2      Bogor

In [221]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cust_id      10 non-null     object
 1   num_of_item  10 non-null     int64
 2   user_city    10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [231]:
df["num_of_item"] = df["num_of_item"].astype("float64")

In [233]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cust_id      10 non-null     object
 1   num_of_item  10 non-null     float64
 2   user_city    10 non-null     object
dtypes: float64(1), object(2)
memory usage: 372.0+ bytes

In [235]:
df

  cust_id  num_of_item  user_city
0      C1          5.0    Jakarta
1      C2          7.0  Tangerang
2      C3          2.0      Bogor
3      C4          4.0    Jakarta
4      C5          5.0  Tangerang
5      C6          2.0      Bogor
6      C7          5.0    Jakarta
7      C8          6.0  Tangerang
8      C9          1.0      Bogor
9     C10          2.0      Bogor

In [239]:
df["num_of_item"] = df["num_of_item"].astype("int64")

In [241]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cust_id      10 non-null     object
 1   num_of_item  10 non-null     int64
 2   user_city    10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [243]:
df

  cust_id  num_of_item  user_city
0      C1            5    Jakarta
1      C2            7  Tangerang
2      C3            2      Bogor
3      C4            4    Jakarta
4      C5            5  Tangerang
5      C6            2      Bogor
6      C7            5    Jakarta
7      C8            6  Tangerang
8      C9            1      Bogor
9     C10            2      Bogor

In [247]:
df["num_of_item"] = df["num_of_item"].astype("object")

In [249]:
df

  cust_id num_of_item  user_city
0      C1           5    Jakarta
1      C2           7  Tangerang
2      C3           2      Bogor
3      C4           4    Jakarta
4      C5           5  Tangerang
5      C6           2      Bogor
6      C7           5    Jakarta
7      C8           6  Tangerang
8      C9           1      Bogor
9     C10           2      Bogor

In [251]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cust_id      10 non-null     object
 1   num_of_item  10 non-null     object
 2   user_city    10 non-null     object
dtypes: object(3)
memory usage: 372.0+ bytes

In [253]:
#data filtering

In [52]:
df = pd.DataFrame({"customer_id" : ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10"],
                  "item_bought" : [5, 7, 2, 4, 5, 2, 5, 6, 1, 2],
                   "city" : ["Jakarta", "Arab", "Bogor", "Jakarta", "Malysia", "Bogor", "Jakarta", "Jawa", "Bogor", "Bogor"]
                  })
df

  customer_id  item_bought       city
0          C1            5    Jakarta
1          C2            7  Tangerang
2          C3            2      Bogor
3          C4            4    Jakarta
4          C5            5  Tangerang
5          C6            2      Bogor
6          C7            5    Jakarta
7          C8            6       Jawa
8          C9            1      Bogor
9         C10            2      Bogor

In [261]:
#loc

In [263]:
#single value

In [265]:
df.loc[0, "customer_id"]

'C1'

In [267]:
df.loc[5, "city"]

'Bogor'

In [269]:
df.loc[2, "item_bought"]

2

In [271]:
#range of rows/columns

In [275]:
df.loc[0:4, "customer_id"]

0    C1
1    C2
2    C3
3    C4
4    C5
Name: customer_id, dtype: object

In [277]:
df.loc[0:4, ["customer_id", "city"]]

  customer_id       city
0          C1    Jakarta
1          C2  Tangerang
2          C3      Bogor
3          C4    Jakarta
4          C5  Tangerang

In [279]:
df.loc[2, ["customer_id", "city"]]

customer_id       C3
city           Bogor
Name: 2, dtype: object

In [281]:
#iloc

In [283]:
df

  customer_id  item_bought       city
0          C1            5    Jakarta
1          C2            7  Tangerang
2          C3            2      Bogor
3          C4            4    Jakarta
4          C5            5  Tangerang
5          C6            2      Bogor
6          C7            5    Jakarta
7          C8            6  Tangerang
8          C9            1      Bogor
9         C10            2      Bogor

In [285]:
#single value

In [287]:
df.iloc[0, 0]

'C1'

In [289]:
df.iloc[2, 2]

'Bogor'

In [291]:
df.iloc[5, 1]

2

In [293]:
 #range of values

In [295]:
df.iloc[0:2, 0]

0    C1
1    C2
Name: customer_id, dtype: object

In [351]:
df.iloc[0:2, 0:3]

  customer_id  item_bought       city
0          C1            5    Jakarta
1          C2            7  Tangerang

In [353]:
#filtering dataframe with criteria

In [355]:
#object

In [10]:
df

  customer_id  item_bought       city
0          C1            5    Jakarta
1          C2            7  Tangerang
2          C3            2      Bogor
3          C4            4    Jakarta
4          C5            5  Tangerang
5          C6            2      Bogor
6          C7            5    Jakarta
7          C8            6  Tangerang
8          C9            1      Bogor
9         C10            2      Bogor

In [20]:
df[(df["city"] == "Jakarta")]

  customer_id  item_bought     city
0          C1            5  Jakarta
3          C4            4  Jakarta
6          C7            5  Jakarta

In [24]:
df[(df["customer_id"] == "C8")]

  customer_id  item_bought       city
7          C8            6  Tangerang

In [26]:
#numeric

In [28]:
df

  customer_id  item_bought       city
0          C1            5    Jakarta
1          C2            7  Tangerang
2          C3            2      Bogor
3          C4            4    Jakarta
4          C5            5  Tangerang
5          C6            2      Bogor
6          C7            5    Jakarta
7          C8            6  Tangerang
8          C9            1      Bogor
9         C10            2      Bogor

In [32]:
df[(df["item_bought"] >= 5)]

  customer_id  item_bought       city
0          C1            5    Jakarta
1          C2            7  Tangerang
4          C5            5  Tangerang
6          C7            5    Jakarta
7          C8            6  Tangerang

In [34]:
#negative of criteria

In [36]:
df

  customer_id  item_bought       city
0          C1            5    Jakarta
1          C2            7  Tangerang
2          C3            2      Bogor
3          C4            4    Jakarta
4          C5            5  Tangerang
5          C6            2      Bogor
6          C7            5    Jakarta
7          C8            6  Tangerang
8          C9            1      Bogor
9         C10            2      Bogor

In [40]:
df[(df["item_bought"] > 5)]

  customer_id  item_bought       city
1          C2            7  Tangerang
7          C8            6  Tangerang

In [42]:
df[~(df["item_bought"] > 5)]

  customer_id  item_bought       city
0          C1            5    Jakarta
2          C3            2      Bogor
3          C4            4    Jakarta
4          C5            5  Tangerang
5          C6            2      Bogor
6          C7            5    Jakarta
8          C9            1      Bogor
9         C10            2      Bogor

In [44]:
#filter dataframe with several criteria(AND)

In [46]:
df

  customer_id  item_bought       city
0          C1            5    Jakarta
1          C2            7  Tangerang
2          C3            2      Bogor
3          C4            4    Jakarta
4          C5            5  Tangerang
5          C6            2      Bogor
6          C7            5    Jakarta
7          C8            6  Tangerang
8          C9            1      Bogor
9         C10            2      Bogor

In [54]:
df[(df["item_bought"] > 5) & (df["city"] != "Tangerang")]

  customer_id  item_bought  city
7          C8            6  Jawa

In [56]:
df[~(df["item_bought"] > 5) & (df["city"] != "Tangerang")]

  customer_id  item_bought     city
0          C1            5  Jakarta
2          C3            2    Bogor
3          C4            4  Jakarta
5          C6            2    Bogor
6          C7            5  Jakarta
8          C9            1    Bogor
9         C10            2    Bogor

In [66]:
df[(df["item_bought"]) > 7 | (df["city"] != "Bogor")]

  customer_id  item_bought       city
0          C1            5    Jakarta
1          C2            7  Tangerang
2          C3            2      Bogor
3          C4            4    Jakarta
4          C5            5  Tangerang
5          C6            2      Bogor
6          C7            5    Jakarta
7          C8            6       Jawa
9         C10            2      Bogor

In [76]:
df[~(df["item_bought"]) > 4 | (df["city"] != "Jakarta")]

Empty DataFrame
Columns: [customer_id, item_bought, city]
Index: []

In [78]:
#filter with isin operation

In [92]:
list_of_cities = ["Jakarta", "Tangerang", "Depok"]

In [94]:
df[(df["city"].isin(list_of_cities))]

  customer_id  item_bought       city
0          C1            5    Jakarta
1          C2            7  Tangerang
3          C4            4    Jakarta
4          C5            5  Tangerang
6          C7            5    Jakarta

In [98]:
list_of_cust = ["C5", "C1", "C7"]

In [100]:
df[(df["customer_id"].isin(list_of_cust))]

  customer_id  item_bought       city
0          C1            5    Jakarta
4          C5            5  Tangerang
6          C7            5    Jakarta

In [102]:
#Case Study

In [108]:
customers = pd.DataFrame({
    "id": [1,2,3,4],
    "name": ["Joko", "Udin", "Ilham", "Sam"]
})

In [112]:
orders = pd.DataFrame({
    "id": [1,2],
    "customer_id": [3,1]
})

In [114]:
customers

   id   name
0   1   Joko
1   2   Udin
2   3  Ilham
3   4    Sam

In [116]:
orders

   id  customer_id
0   1            3
1   2            1

In [122]:
id_order_list = list(orders["customer_id"])

In [124]:
id_order_list

[3, 1]

In [128]:
customers[(customers["id"].isin(id_order_list))]

   id   name
0   1   Joko
2   3  Ilham

In [138]:
df_customer_not_order = customers[~(customers["id"].isin(id_order_list))].sort_values(by = "name", ascending = True).reset_index(drop = True)

In [140]:
df_customer_not_order

   id  name
0   4   Sam
1   2  Udin

In [142]:
df_customer_not_order["name"]

0     Sam
1    Udin
Name: name, dtype: object

In [148]:
list_name =list(df_customer_not_order["name"])

In [150]:
list_name

['Sam', 'Udin']

In [152]:
result = pd.DataFrame({
    'inactive_cust': list_name
})

In [154]:
result

  inactive_cust
0           Sam
1          Udin

In [156]:
#data_agregation

In [162]:
iris = pd.read_csv("https://gist.githubusercontent.com/thomasnield/03cf7c08016b514086ac8a9fdc07cc65/raw/bf4bb9d96e44bd8e7fbac3df6a2d779f439b3dc5/iris.csv")

In [186]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [188]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [168]:
#value counts

In [170]:
iris["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [174]:
iris["petal_length"].value_counts()

petal_length
1.5    14
1.4    12
5.1     8
4.5     8
1.6     7
1.3     7
5.6     6
4.7     5
4.9     5
4.0     5
4.2     4
5.0     4
4.4     4
4.8     4
1.7     4
3.9     3
4.6     3
5.7     3
4.1     3
5.5     3
6.1     3
5.8     3
3.3     2
5.4     2
6.7     2
5.3     2
5.9     2
6.0     2
1.2     2
4.3     2
1.9     2
3.5     2
5.2     2
3.0     1
1.1     1
3.7     1
3.8     1
6.6     1
6.3     1
1.0     1
6.9     1
3.6     1
6.4     1
Name: count, dtype: int64

In [190]:
#group by, agregation

In [196]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [200]:
iris.groupby(["species"]).count()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50

In [202]:
iris.groupby(["species"]).min()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

In [204]:
iris.groupby(["species"]).max()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

In [206]:
iris.groupby(["species"]).sum()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             250.3        170.9          73.2         12.2
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [208]:
iris.groupby(["species"]).mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [210]:
iris.groupby(["species"]).median()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.0          3.4          1.50          0.2
versicolor           5.9          2.8          4.35          1.3
virginica            6.5          3.0          5.55          2.0

In [212]:
iris.groupby(["species"]).describe()

           sepal_length                                              \
                  count   mean       std  min    25%  50%  75%  max
species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal_width         ... petal_length      petal_width         \
                 count   mean  ...          75%  max       count   mean
species                        ...
setosa            50.0  3.418  ...        1.575  1.9        50.0  0.244
versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
species
setosa      0.107210  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [214]:
iris.groupby(["species"]).describe().T

species                setosa  versicolor  virginica
sepal_length count  50.000000   50.000000  50.000000
             mean    5.006000    5.936000   6.588000
             std     0.352490    0.516171   0.635880
             min     4.300000    4.900000   4.900000
             25%     4.800000    5.600000   6.225000
             50%     5.000000    5.900000   6.500000
             75%     5.200000    6.300000   6.900000
             max     5.800000    7.000000   7.900000
sepal_width  count  50.000000   50.000000  50.000000
             mean    3.418000    2.770000   2.974000
             std     0.381024    0.313798   0.322497
             min     2.300000    2.000000   2.200000
             25%     3.125000    2.525000   2.800000
             50%     3.400000    2.800000   3.000000
             75%     3.675000    3.000000   3.175000
             max     4.400000    3.400000   3.800000
petal_length count  50.000000   50.000000  50.000000
             mean    1.464000    4.260000   5.552000
             std     0.173511    0.469911   0.551895
             min     1.000000    3.000000   4.500000
             25%     1.400000    4.000000   5.100000
             50%     1.500000    4.350000   5.550000
             75%     1.575000    4.600000   5.875000
             max     1.900000    5.100000   6.900000
petal_width  count  50.000000   50.000000  50.000000
             mean    0.244000    1.326000   2.026000
             std     0.107210    0.197753   0.274650
             min     0.100000    1.000000   1.400000
             25%     0.200000    1.200000   1.800000
             50%     0.200000    1.300000   2.000000
             75%     0.300000    1.500000   2.300000
             max     0.600000    1.800000   2.500000

In [224]:
df = iris.groupby(["species"]).mean().reset_index()
df

      species  sepal_length  sepal_width  petal_length  petal_width
0      setosa         5.006        3.418         1.464        0.244
1  versicolor         5.936        2.770         4.260        1.326
2   virginica         6.588        2.974         5.552        2.026

In [226]:
df[(df["species"] == "setosa")]

  species  sepal_length  sepal_width  petal_length  petal_width
0  setosa         5.006        3.418         1.464        0.244

In [228]:
iris.groupby(["species"]).agg(["min", "max"])

           sepal_length      sepal_width      petal_length      petal_width  \
                    min  max         min  max          min  max         min
species
setosa              4.3  5.8         2.3  4.4          1.0  1.9         0.1
versicolor          4.9  7.0         2.0  3.4          3.0  5.1         1.0
virginica           4.9  7.9         2.2  3.8          4.5  6.9         1.4


            max
species
setosa      0.6
versicolor  1.8
virginica   2.5

In [236]:
iris.groupby(["species"]).agg({"sepal_length": ["min", "sum"], "sepal_width": ["max", "mean"]})

           sepal_length        sepal_width
                    min    sum         max   mean
species
setosa              4.3  250.3         4.4  3.418
versicolor          4.9  296.8         3.4  2.770
virginica           4.9  329.4         3.8  2.974

In [238]:
#data merging

In [242]:
df1 = pd.DataFrame({
    "cust_id": ["C1", "C2", "C3", "C4", "C5"],
    "item_bought": [10,15,20,35,4],
    "city": ["Bandung", "Bali", "Jakarta", "Bogor", "Tangerang"]
})
df1

  cust_id  item_bought       city
0      C1           10    Bandung
1      C2           15       Bali
2      C3           20    Jakarta
3      C4           35      Bogor
4      C5            4  Tangerang

In [250]:
df3 = pd.DataFrame({
    "cust_no": ["C1", "C2", "C3", "C5", "C6", "C7", "C8"],
    "age": [24,31,23,40,35,28,34]
})
df3

  cust_no  age
0      C1   24
1      C2   31
2      C3   23
3      C5   40
4      C6   35
5      C7   28
6      C8   34

In [258]:
df1.merge(df3, how = "left", left_on = "cust_id", right_on = "cust_no")

  cust_id  item_bought       city cust_no   age
0      C1           10    Bandung      C1  24.0
1      C2           15       Bali      C2  31.0
2      C3           20    Jakarta      C3  23.0
3      C4           35      Bogor     NaN   NaN
4      C5            4  Tangerang      C5  40.0

In [262]:
df1.merge(df3, how = "right", left_on = "cust_id", right_on = "cust_no")

  cust_id  item_bought       city cust_no  age
0      C1         10.0    Bandung      C1   24
1      C2         15.0       Bali      C2   31
2      C3         20.0    Jakarta      C3   23
3      C5          4.0  Tangerang      C5   40
4     NaN          NaN        NaN      C6   35
5     NaN          NaN        NaN      C7   28
6     NaN          NaN        NaN      C8   34

In [266]:
df3.merge(df1, how = "right", left_on = "cust_no", right_on = "cust_id")

  cust_no   age cust_id  item_bought       city
0      C1  24.0      C1           10    Bandung
1      C2  31.0      C2           15       Bali
2      C3  23.0      C3           20    Jakarta
3     NaN   NaN      C4           35      Bogor
4      C5  40.0      C5            4  Tangerang

In [268]:
df1.merge(df3, how = "inner", left_on = "cust_id", right_on = "cust_no")

  cust_id  item_bought       city cust_no  age
0      C1           10    Bandung      C1   24
1      C2           15       Bali      C2   31
2      C3           20    Jakarta      C3   23
3      C5            4  Tangerang      C5   40

In [272]:
df1.merge(df3, how = "outer", left_on = "cust_id", right_on = "cust_no")

  cust_id  item_bought       city cust_no   age
0      C1         10.0    Bandung      C1  24.0
1      C2         15.0       Bali      C2  31.0
2      C3         20.0    Jakarta      C3  23.0
3      C4         35.0      Bogor     NaN   NaN
4      C5          4.0  Tangerang      C5  40.0
5     NaN          NaN        NaN      C6  35.0
6     NaN          NaN        NaN      C7  28.0
7     NaN          NaN        NaN      C8  34.0

In [276]:
df1.merge(df3, how = "inner", left_on = "cust_id", right_on = "cust_no").drop(columns = ["cust_no"])

  cust_id  item_bought       city  age
0      C1           10    Bandung   24
1      C2           15       Bali   31
2      C3           20    Jakarta   23
3      C5            4  Tangerang   40